# Generated by Django 3.1.1 on 2021-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name', models.CharField(max_length=30, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=100, unique=True, verbose_name='Password')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('contact', models.IntegerField(verbose_name='Contact')),
                ('dob', models.DateField(verbose_name='Event Date')),
                ('speciality', models.CharField(max_length=100, verbose_name='Speciality')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20, verbose_name='Gender')),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+')], max_length=10, verbose_name='Blood')),
            ],
            options={
                'db_table': 'Doctor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Patient Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('contact', models.IntegerField(verbose_name='Contact')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20, verbose_name='Gender')),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+')], max_length=10, verbose_name='Blood')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
            ],
            options={
                'db_table': 'Patient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient_trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Patient Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('contact', models.IntegerField(verbose_name='Contact')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20, verbose_name='Gender')),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+')], max_length=10, verbose_name='Blood')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
            ],
            options={
                'db_table': 'Patient_trash',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(verbose_name='Patient ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('prescription', models.CharField(max_length=300, verbose_name='Prescription')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'db_table': 'Prescription',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100, unique=True, verbose_name='Userame')),
                ('name', models.CharField(max_length=30, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=100, unique=True, verbose_name='Password')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('contact', models.IntegerField(verbose_name='Contact')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20, verbose_name='Gender')),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+')], max_length=10, verbose_name='Blood')),
            ],
            options={
                'db_table': 'Receptionist',
                'ordering': ['name'],
            },
        ),
    ]
