# Generated by Django 3.1.1 on 2021-03-11 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='patient_trash',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact'),
        ),
    ]
