# Generated by Django 3.1.1 on 2021-03-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0002_auto_20210311_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='patient_trash',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is_deleted'),
        ),
    ]
